### ISSUE TITLE
Bug on Binary Watch problem

### ISSUE THREAD

**Issue by weebao** [beatcode-official/beatcode-server#14]
How to reproduce: Submit correct submission on "Binary Watch" problem.

```bash
Traceback (most recent call last): File "/code/tmphom585pw.py", line 57, in 
run_tests passed = compare_results(result, test['expected']) 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/code/tmphom585pw.py", line 22, in 
compare_results return sorted_list_strings(result) == sorted_list_strings(expected) 
^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
File "/code/tmphom585pw.py", line 21, 
in sorted_list_strings return sorted([str(x) for x in eval(lst)]) 
^^^^^^^^^ 
TypeError: eval() arg 1 must be a string, bytes or code object
```

**Comment by hdngo** [comment]
I think you still have the old problem database, please re-init
